### ISSUE TITLE
initial_query both in system message and user message

### ISSUE THREAD

**Issue by nitinrathi** [codelion/optillm#2]
Why are we sending the `initial_query` twice, once in [system message](https://github.com/codelion/optillm/blob/8f1090d2415042a7d39b0fa07ea374fee0958645/cot_reflection.py#L34) as cot_prompt and once in [user message
](https://github.com/codelion/optillm/blob/8f1090d2415042a7d39b0fa07ea374fee0958645/cot_reflection.py#L42), does it improve performance?

**Comment by codelion** [comment]
Thanks for catching it, it wasn't intentional I will remove the initial_query from system message. I am trying out a different variation of the prompt with 2 separate stages 1) for Cot and 2) for Reflection. This is based on the observation that the reflection part of the response doesn't change the initial thinking in most of the cases while running with GSM8k benchmark. I will fix this along with that update once I have the updated numbers from the benchmark.
